<!DOCTYPE html>
<html lang="es"><head>
<script src="unidad-02_sesion-02_files/libs/clipboard/clipboard.min.js"></script>
<script src="unidad-02_sesion-02_files/libs/quarto-html/tabby.min.js"></script>
<script src="unidad-02_sesion-02_files/libs/quarto-html/popper.min.js"></script>
<script src="unidad-02_sesion-02_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="unidad-02_sesion-02_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="unidad-02_sesion-02_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="unidad-02_sesion-02_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <title>Unidad 2 — El agua en el suelo</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="unidad-02_sesion-02_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="unidad-02_sesion-02_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="unidad-02_sesion-02_files/libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link href="unidad-02_sesion-02_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="unidad-02_sesion-02_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="unidad-02_sesion-02_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="unidad-02_sesion-02_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Unidad 2 — El agua en el suelo</h1>
  <p class="subtitle">Sesión 2.2: Relaciones masa-volumen de suelo</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="recapitulación-sesión-anterior" class="slide level2 center">
<h2>Recapitulación sesión anterior</h2>
<div style="font-size: 0.85em;">
<p><strong>Sesión 2.1 — Ideas fuerza:</strong><br>
- Textura + estructura + MO determinan la capacidad de retención de agua<br>
- Ψm mide la succión con que el suelo retiene el agua<br>
- La curva característica θ(Ψm) es la huella digital hídrica</p>
<p><strong>Hoy:</strong> Pasamos de lo cualitativo a lo <strong>cuantitativo</strong>: ¿cómo medimos la densidad y porosidad del suelo?</p>
</div>
</section>
<section id="información-de-la-sesión" class="slide level2 center">
<h2>Información de la sesión</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Unidad</strong></td>
<td>2 — El agua en el suelo</td>
</tr>
<tr class="even">
<td><strong>Sesión</strong></td>
<td>2.2</td>
</tr>
<tr class="odd">
<td><strong>RAA</strong></td>
<td>RAA3</td>
</tr>
<tr class="even">
<td><strong>Duración</strong></td>
<td>~90 minutos</td>
</tr>
<tr class="odd">
<td><strong>Contenido</strong></td>
<td>Densidad aparente, densidad real, porosidad total, relaciones masa-volumen</td>
</tr>
</tbody>
</table>
</section>
<section id="objetivos-de-aprendizaje" class="slide level2 center">
<h2>Objetivos de aprendizaje</h2>
<p>Al finalizar esta sesión, serás capaz de:</p>
<ol type="1">
<li>Definir y calcular la densidad aparente (Da) por el método del cilindro</li>
<li>Definir y calcular la densidad real (Dr) por el método del picnómetro</li>
<li>Calcular la porosidad total a partir de Da y Dr</li>
<li>Interpretar valores de Da como indicador de compactación</li>
<li>Relacionar Da con la conversión θg → θv</li>
</ol>
</section>
<section id="por-qué-importan-estas-relaciones" class="slide level2 center smaller">
<h2>¿Por qué importan estas relaciones?</h2>
<p>Para calcular cuánta agua hay en el suelo necesitamos tres números:</p>
<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 25%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>¿Qué mide?</th>
<th>¿Por qué la necesito?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Da</strong></td>
<td>Masa seca / Volumen total</td>
<td>Convierte masa de suelo a volumen</td>
</tr>
<tr class="even">
<td><strong>Dr</strong></td>
<td>Masa seca / Volumen de sólidos</td>
<td>Permite calcular espacio poroso</td>
</tr>
<tr class="odd">
<td><strong>Porosidad</strong></td>
<td>% del volumen que son poros</td>
<td>Límite máximo de agua que cabe</td>
</tr>
</tbody>
</table>
<div style="margin-top: 2em; text-align: center; font-weight: bold;">
<p><span class="math inline">\(\theta_v = \theta_g \times \frac{D_a}{\rho_{agua}}\)</span> — Sin Da no hay conversión posible</p>
</div>
</section>
<section id="esquema-componentes-del-volumen-de-suelo" class="slide level2 center">
<h2>Esquema: componentes del volumen de suelo</h2>

<img data-src="../../images/agua_en_el_suelo.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="densidad-aparente-da" class="slide level2 center">
<h2>Densidad aparente (Da)</h2>
<p><strong>Definición:</strong> Masa de suelo seco (105°C) por unidad de volumen total (incluyendo poros).</p>
<p><span class="math display">\[D_a = \frac{M_s}{V_t} \quad [\text{g/cm}^3 \text{ o Mg/m}^3]\]</span></p>
<p><strong>¿Qué mide realmente Da?</strong> - No mide la densidad de las partículas<br>
- Mide cuán “empacado” está el suelo<br>
- Da alta = partículas más juntas = menos poros = más compactado<br>
- Da baja = más espacio poroso = menos compactado</p>
</section>
<section id="método-del-cilindro-para-determinar-da" class="slide level2 center">
<h2>Método del cilindro para determinar Da</h2>
<div style="font-size: 0.9em;">
<p><strong>Procedimiento paso a paso: <a href="https://www.youtube.com/watch?v=pOQcfaw7UEk">Video</a></strong></p>
<ol type="1">
<li><p><strong>Insertar</strong> cilindro metálico de volumen conocido (típicamente 100 cm³) en el suelo sin disturbar. Usar un martillo y un bloque de madera para inserción pareja.</p></li>
<li><p><strong>Extraer</strong> cuidadosamente con pala o cuchillo, evitando vibraciones que compacten o expandan la muestra.</p></li>
<li><p><strong>Enrasar</strong> ambos extremos del cilindro con cuchillo o espátula (quitar exceso, NO compactar).</p></li>
<li><p><strong>Transferir</strong> todo el suelo del cilindro a una bolsa o recipiente. Pesar inmediatamente (masa húmeda).</p></li>
<li><p><strong>Secar</strong> en estufa a 105°C durante 24 horas.</p></li>
<li><p><strong>Pesar</strong> la muestra seca (Ms). Calcular: <span class="math inline">\(D_a = M_s / V_{cilindro}\)</span></p></li>
</ol>
</div>
</section>
<section id="errores-comunes-en-la-medición-de-da" class="slide level2 center smaller">
<h2>Errores comunes en la medición de Da</h2>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 37%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Error</th>
<th>Efecto en Da</th>
<th>Cómo evitarlo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Compactar al insertar el cilindro</td>
<td><strong>Sobreestima</strong> Da</td>
<td>Insertar suavemente, sin golpes fuertes</td>
</tr>
<tr class="even">
<td>Dejar piedras o gravas en la muestra</td>
<td><strong>Sobreestima</strong> (Dr de grava &gt; suelo)</td>
<td>Tamizar o usar método del terrón</td>
</tr>
<tr class="odd">
<td>Perder material al extraer</td>
<td><strong>Subestima</strong> Da (menos Ms)</td>
<td>Extraer con cuidado, usar bolsa</td>
</tr>
<tr class="even">
<td>No secar completamente</td>
<td><strong>Subestima</strong> Da (Ms incluye agua)</td>
<td>105°C × 24h mínimo; verificar peso constante</td>
</tr>
<tr class="odd">
<td>Suelo muy húmedo al muestrear</td>
<td>Se expande → <strong>subestima</strong> Da</td>
<td>Muestrear a humedad de campo, no después de lluvia</td>
</tr>
</tbody>
</table>
</section>
<section id="valores-típicos-e-interpretación-de-da" class="slide level2 center smaller">
<h2>Valores típicos e interpretación de Da</h2>
<table class="caption-top">
<colgroup>
<col style="width: 21%">
<col style="width: 27%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Da (g/cm³)</th>
<th>Tipo de suelo</th>
<th>Interpretación agronómica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.2 - 0.6</td>
<td>Turbas, suelo muy orgánico</td>
<td>Excelente porosidad, baja capacidad de soporte</td>
</tr>
<tr class="even">
<td>0.7 - 1.0</td>
<td>Arcilloso bien estructurado</td>
<td>Alta porosidad, buen desarrollo radical</td>
</tr>
<tr class="odd">
<td>1.0 - 1.3</td>
<td>Franco-arcilloso, arcilloso</td>
<td>Buen balance para cultivos</td>
</tr>
<tr class="even">
<td>1.3 - 1.5</td>
<td>Franco, franco-arenoso</td>
<td>Ideal para la mayoría de cultivos</td>
</tr>
<tr class="odd">
<td>1.5 - 1.7</td>
<td>Franco-arenoso, arenoso</td>
<td>Aceptable; monitorear compactación</td>
</tr>
<tr class="even">
<td>1.7 - 1.9</td>
<td>Compactado (cualquier textura)</td>
<td><strong>Restricción moderada</strong> al crecimiento radical</td>
</tr>
<tr class="odd">
<td>&gt; 1.9</td>
<td>Severamente compactado</td>
<td><strong>Restricción severa</strong> — requiere subsolado</td>
</tr>
</tbody>
</table>
</section>
<section id="da-como-indicador-de-compactación" class="slide level2 center">
<h2>Da como indicador de compactación</h2>
<p><strong>Regla práctica:</strong> Da &gt; 1.6 g/cm³ en suelos francos ya restringe raíces.</p>
<table class="caption-top">
<colgroup>
<col style="width: 21%">
<col style="width: 45%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Cultivo</th>
<th>Da crítica (g/cm³)</th>
<th>Consecuencia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hortalizas, papa</td>
<td>1.5 - 1.6</td>
<td>Tubérculos deformes, menor calibre</td>
</tr>
<tr class="even">
<td>Maíz, trigo</td>
<td>1.6 - 1.7</td>
<td>Menor profundidad radical, menos agua disponible</td>
</tr>
<tr class="odd">
<td>Frutales</td>
<td>1.7 - 1.8</td>
<td>Raíces superficiales, vuelco</td>
</tr>
<tr class="even">
<td>Praderas</td>
<td>&gt; 1.7</td>
<td>Menor densidad de raíces, menor infiltración</td>
</tr>
</tbody>
</table>
<div style="font-size: 0.8em; margin-top: 0.5em;">
<p>La Da crítica depende de la textura: en arcillosos es menor (~1.5) que en arenosos (~1.8).</p>
</div>
</section>
<section id="ejercicio-rápido-densidad-aparente" class="slide level2 center">
<h2>Ejercicio rápido: densidad aparente</h2>
<p>Un cilindro de 100 cm³ de suelo seco pesa 145 g.</p>
<ol type="1">
<li>Calcula la Da.</li>
<li>¿El suelo está compactado? (usa la tabla de interpretación)</li>
<li>Si el mismo suelo tuviera Da = 1.2 g/cm³, ¿qué habría cambiado en el campo?</li>
</ol>
<div style="font-size: 0.8em; text-align: center; margin-top: 1em;">
<p>Resuelve en 4 minutos.</p>
</div>
<aside class="notes">
<ol type="1">
<li>Da = 145/100 = 1.45 g/cm³ (franco, rango ideal). 2. No, está en rango óptimo. 3. Más porosidad → menos compactación (más MO, menos tráfico, mejor estructura).</li>
</ol>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="densidad-real-dr-definición-y-valores" class="slide level2 center smaller">
<h2>Densidad real (Dr): definición y valores</h2>
<p><strong>Definición:</strong> Masa de suelo seco por unidad de volumen de partículas sólidas (sin poros).</p>
<p><span class="math display">\[D_r = \frac{M_s}{V_s} \quad [\text{g/cm}^3]\]</span></p>
<p><strong>Valores típicos según composición mineral:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>Mineral</th>
<th>Dr (g/cm³)</th>
<th>Abundancia en suelos chilenos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cuarzo (SiO₂)</td>
<td>2.65</td>
<td>Muy abundante (fracción arena y limo)</td>
</tr>
<tr class="even">
<td>Feldespatos</td>
<td>2.55 - 2.75</td>
<td>Abundantes</td>
</tr>
<tr class="odd">
<td>Caolinita (arcilla 1:1)</td>
<td>2.60 - 2.65</td>
<td>Común en suelos de la zona central</td>
</tr>
<tr class="even">
<td>Montmorillonita (arcilla 2:1)</td>
<td>2.2 - 2.7</td>
<td>Suelos volcánicos (sur de Chile)</td>
</tr>
<tr class="odd">
<td>Materia orgánica</td>
<td>1.3 - 1.5</td>
<td>Variable</td>
</tr>
<tr class="even">
<td>Calcita (CaCO₃)</td>
<td>2.71</td>
<td>Suelos calcáreos (norte)</td>
</tr>
</tbody>
</table>
<div style="margin-top: 0.5em; font-weight: bold; text-align: center;">
<p>Para la mayoría de suelos minerales chilenos: Dr ≈ 2.65 g/cm³</p>
</div>
</section>
<section id="método-del-picnómetro-para-dr" class="slide level2 center smaller">
<h2>Método del picnómetro para Dr</h2>
<div style="font-size: 0.85em;">
<p><strong>Procedimiento:</strong></p>
<ol type="1">
<li>Pesar picnómetro vacío y seco → <span class="math inline">\(P_{vacio}\)</span></li>
<li>Agregar ≈10-20 g de suelo seco y tamizado (&lt; 2 mm) → <span class="math inline">\(P_{vacio+suelo}\)</span>; <span class="math inline">\(M_s = P_{vacio+suelo} - P_{vacio}\)</span></li>
<li>Agregar agua destilada hasta ~2/3 del volumen</li>
<li><strong>Hervir suavemente</strong> 10-15 min para eliminar aire atrapado en poros del suelo</li>
<li>Enfriar, enrasar con agua destilada, pesar → <span class="math inline">\(P_{vacio+suelo+agua}\)</span></li>
<li>Vaciar, limpiar, llenar solo con agua destilada, enrasar, pesar → <span class="math inline">\(P_{vacio+agua}\)</span></li>
</ol>
<p><strong>Cálculo:</strong></p>
<p><span class="math display">\[D_r = \frac{M_s \times \rho_{agua}}{M_s - (P_{vacio+suelo+agua} - P_{vacio+agua})}\]</span></p>
<div style="font-size: 0.8em; margin-top: 0.3em;">
<p>En la práctica del curso: asumimos Dr = 2.65 g/cm³ (suelo mineral típico).</p>
</div>
</div>
</section>
<section id="ejercicio-densidad-real" class="slide level2 center">
<h2>Ejercicio: densidad real</h2>
<ol type="1">
<li>¿Por qué Dr (≈2.65) es siempre mayor que Da (≈1.3–1.6)?</li>
<li>¿Qué volumen mide Da que Dr no incluye?</li>
<li>Un suelo muy orgánico tiene Dr = 1.5. ¿Por qué es tan baja?</li>
</ol>
<div style="font-size: 0.8em; text-align: center; margin-top: 1em;">
<p>Resuelve en 3 minutos.</p>
</div>
<aside class="notes">
<ol type="1">
<li>Dr solo considera sólidos (sin poros). 2. Da incluye los poros (volumen total). 3. La MO tiene densidad ~1.3–1.5, mucho menor que los minerales (~2.65).</li>
</ol>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="porosidad-total-p" class="slide level2 center smaller">
<h2>Porosidad total (P)</h2>
<p><strong>Definición:</strong> Fracción del volumen total del suelo ocupada por espacios vacíos (poros).</p>
<p><strong>Fórmula fundamental:</strong> <span class="math display">\[P = \frac{V_p}{V_t} = \frac{V_t - V_s}{V_t} = 1 - \frac{V_s}{V_t}\]</span></p>
<p><strong>En función de densidades (lo que usamos en la práctica):</strong> <span class="math display">\[P = 1 - \frac{D_a}{D_r}\]</span> <span class="math display">\[P(\%) = \left(1 - \frac{D_a}{D_r}\right) \times 100\]</span></p>
<p><strong>Interpretación:</strong><br>
- P = 30% → suelo compactado, pocos poros<br>
- P = 50% → suelo agrícola en buenas condiciones<br>
- P = 65% → suelo muy poroso (orgánico o arcilloso muy estructurado)</p>
</section>
<section id="ejemplo-completo-de-cálculo" class="slide level2 center smaller">
<h2>Ejemplo completo de cálculo</h2>
<p><strong>Datos de campo:</strong><br>
- Cilindro metálico: diámetro = 5.0 cm, altura = 5.1 cm<br>
- Masa de suelo húmedo extraído: 185.0 g<br>
- Masa después de secado (105°C, 24h): 157.0 g<br>
- Dr asumida: 2.65 g/cm³</p>
<p><strong>Paso 1 — Volumen del cilindro:</strong> <span class="math inline">\(V_t = \pi \times (2.5)^2 \times 5.1 = 100.1 \text{ cm}^3\)</span></p>
<p><strong>Paso 2 — Densidad aparente:</strong> <span class="math inline">\(D_a = 157.0 / 100.1 = 1.57 \text{ g/cm}^3\)</span></p>
<p><strong>Paso 3 — Porosidad:</strong> <span class="math inline">\(P = (1 - 1.57 / 2.65) \times 100 = 40.8\%\)</span></p>
<p><strong>Interpretación:</strong> Suelo arenoso-franco, Da media-alta. Posible compactación incipiente.</p>
</section>
<section id="la-relación-da-porosidad" class="slide level2 center">
<h2>La relación Da ↔︎ Porosidad</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Da (g/cm³)</th>
<th>P (%) con Dr=2.65</th>
<th>Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.80</td>
<td>69.8</td>
<td>Muy poroso (orgánico)</td>
</tr>
<tr class="even">
<td>1.00</td>
<td>62.3</td>
<td>Muy poroso (arcilloso bien estructurado)</td>
</tr>
<tr class="odd">
<td>1.20</td>
<td>54.7</td>
<td>Buen suelo agrícola</td>
</tr>
<tr class="even">
<td>1.35</td>
<td>49.1</td>
<td><strong>Ideal</strong> para mayoría de cultivos</td>
</tr>
<tr class="odd">
<td>1.50</td>
<td>43.4</td>
<td>Aceptable, monitorear</td>
</tr>
<tr class="even">
<td>1.65</td>
<td>37.7</td>
<td><strong>Compactación moderada</strong> — actuar</td>
</tr>
<tr class="odd">
<td>1.80</td>
<td>32.1</td>
<td><strong>Compactación severa</strong> — subsolar</td>
</tr>
</tbody>
</table>
<div style="margin-top: 1em; font-size: 0.85em;">
<p>Cada 0.1 g/cm³ de aumento en Da ≈ 3.8% de pérdida de porosidad.</p>
</div>
</section>
<section id="aplicación-práctica-cuánta-agua-cabe-en-este-suelo" class="slide level2 center smaller">
<h2>Aplicación práctica: ¿cuánta agua cabe en este suelo?</h2>
<p><strong>Datos del ejemplo anterior:</strong><br>
- Da = 1.57 g/cm³, P = 40.8%<br>
- Si el suelo está a CC (θv ≈ 55% de P en suelo arenoso-franco):</p>
<p><span class="math display">\[\theta_{v,CC} \approx 0.408 \times 0.55 = 0.224 \text{ cm}^3/\text{cm}^3\]</span></p>
<p><strong>Lámina de agua a CC en 1 metro de profundidad:</strong></p>
<p><span class="math display">\[L_{CC} = 0.224 \times 1000 \text{ mm} = 224 \text{ mm}\]</span></p>
<div style="margin-top: 1em; font-weight: bold; text-align: center;">
<p>De esos 224 mm, solo ~120 mm son agua disponible (ADT). El resto es agua gravitacional o no disponible.</p>
</div>
</section>
<section id="relación-entre-da-dr-y-p-tabla-resumen" class="slide level2 center smaller">
<h2>Relación entre Da, Dr y P: tabla resumen</h2>
<table class="caption-top">
<colgroup>
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 10%">
<col style="width: 21%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Suelo</th>
<th>Da (g/cm³)</th>
<th>Dr (g/cm³)</th>
<th>P (%)</th>
<th>¿Compactado?</th>
<th>Calidad física</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Arenoso suelto</td>
<td>1.55</td>
<td>2.65</td>
<td>41.5</td>
<td>No</td>
<td>Buena</td>
</tr>
<tr class="even">
<td>Franco agrícola</td>
<td>1.35</td>
<td>2.65</td>
<td>49.1</td>
<td>No</td>
<td>Muy buena</td>
</tr>
<tr class="odd">
<td>Franco compactado</td>
<td>1.70</td>
<td>2.65</td>
<td>35.8</td>
<td><strong>Sí</strong></td>
<td>Mala</td>
</tr>
<tr class="even">
<td>Arcilloso estructurado</td>
<td>1.10</td>
<td>2.65</td>
<td>58.5</td>
<td>No</td>
<td>Excelente</td>
</tr>
<tr class="odd">
<td>Orgánico (pradera)</td>
<td>0.60</td>
<td>1.80</td>
<td>66.7</td>
<td>No</td>
<td>Excelente</td>
</tr>
<tr class="even">
<td>Franco con piedemonte</td>
<td>1.60</td>
<td>2.68</td>
<td>40.3</td>
<td>Moderada</td>
<td>Regular</td>
</tr>
</tbody>
</table>
</section>
<section id="ejercicio-1-cálculo-básico" class="slide level2 center">
<h2>Ejercicio 1: cálculo básico</h2>
<p>Un cilindro de 100 cm³ extrae una muestra de suelo franco. Después de secar a 105°C por 24h, la masa seca es de 142 g. Asuma Dr = 2.65 g/cm³.</p>
<p><strong>Calcule:</strong><br>
1. Densidad aparente (Da)<br>
2. Volumen de sólidos (Vs)<br>
3. Volumen de poros (Vp)<br>
4. Porosidad total (P) en %<br>
5. ¿El suelo está compactado? Justifique.</p>
<div style="font-size: 0.8em; text-align: center; margin-top: 1em;">
<p>Resuelva en 5 minutos. Revise con su compañero.</p>
</div>
</section>
<section id="ejercicio-2-interpretación-de-datos-de-campo" class="slide level2 center">
<h2>Ejercicio 2: interpretación de datos de campo</h2>
<p>Se muestrearon 3 sectores de un mismo predio frutal:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Sector</th>
<th>Da (g/cm³)</th>
<th>Dr (g/cm³)</th>
<th>P (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Entre hileras (tráfico)</td>
<td>1.72</td>
<td>2.65</td>
<td>?</td>
</tr>
<tr class="even">
<td>Bajo la hilera (goteo)</td>
<td>1.28</td>
<td>2.65</td>
<td>?</td>
</tr>
<tr class="odd">
<td>Cabecera (sin tráfico)</td>
<td>1.38</td>
<td>2.65</td>
<td>?</td>
</tr>
</tbody>
</table>
<p><strong>Calcule:</strong> 1. Porosidad de cada sector 2. ¿Qué sector tiene problemas de compactación? 3. ¿Qué recomendaría al agricultor?</p>
</section>
<section id="variabilidad-espacial-de-la-densidad-aparente" class="slide level2 center smaller">
<h2>Variabilidad espacial de la densidad aparente</h2>
<div style="font-size: 0.9em;">
<p>En un mismo predio, Da puede variar significativamente:</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 38%">
<col style="width: 45%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Zona del predio</th>
<th>Da típica (g/cm³)</th>
<th>Causa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bajo hilera de cultivo</td>
<td>1.20 - 1.35</td>
<td>Sin tráfico, acumulación de MO</td>
</tr>
<tr class="even">
<td>Entre hileras</td>
<td>1.40 - 1.60</td>
<td>Tráfico ocasional</td>
</tr>
<tr class="odd">
<td>Huella de tractor</td>
<td>1.65 - 1.85</td>
<td>Compactación severa por paso repetido</td>
</tr>
<tr class="even">
<td>Cabecera del campo</td>
<td>1.55 - 1.75</td>
<td>Giro de maquinaria concentra tráfico</td>
</tr>
</tbody>
</table>
<p><strong>Implicancia para el riego:</strong> Distinta Da → distinta porosidad → distinta infiltración. El agua no se infiltra uniformemente.</p>
</div>
</section>
<section id="efecto-del-manejo-en-la-da-a-largo-plazo" class="slide level2 center smaller">
<h2>Efecto del manejo en la Da a largo plazo</h2>
<table class="caption-top">
<colgroup>
<col style="width: 38%">
<col style="width: 25%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Práctica de manejo</th>
<th>Efecto en Da</th>
<th>Tiempo de respuesta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Labranza convencional (arado)</td>
<td>↓ Da temporal (afloja), luego ↑ (asentamiento)</td>
<td>Inmediato → 2-3 años</td>
</tr>
<tr class="even">
<td>Cero labranza + cobertura</td>
<td>↓ Da gradual (mejora estructura)</td>
<td>3-7 años</td>
</tr>
<tr class="odd">
<td>Incorporación de compost (20 ton/ha)</td>
<td>↓ Da 0.05-0.15 g/cm³</td>
<td>1-3 años</td>
</tr>
<tr class="even">
<td>Subsolado</td>
<td>↓ Da 0.2-0.4 g/cm³ inmediato</td>
<td>Inmediato → 2-4 años</td>
</tr>
<tr class="odd">
<td>Tráfico controlado (mismas huellas)</td>
<td>↑ Da solo en huellas, ↓ en resto</td>
<td>2-5 años</td>
</tr>
</tbody>
</table>
</section>
<section id="ejercicio-3-de-da-a-lámina-de-agua" class="slide level2 center">
<h2>Ejercicio 3: de Da a lámina de agua</h2>
<p><strong>Datos:</strong><br>
- Muestra de suelo: V_cilindro = 98 cm³, M_húmedo = 172 g, M_seco = 148 g<br>
- Dr = 2.65 g/cm³</p>
<p><strong>Calcule:</strong><br>
1. Da<br>
2. Porosidad total<br>
3. Contenido gravimétrico de agua (θg)<br>
4. Contenido volumétrico de agua (θv)<br>
5. Si este suelo está a CC (Ψm = -33 kPa) y θv_actual es la calculada, ¿está bien regado o necesita riego?</p>
</section>
<section id="resumen-de-conceptos-clave" class="slide level2 center">
<h2>Resumen de conceptos clave</h2>
<ol type="1">
<li><p><strong>Da</strong> = Masa seca / Volumen total (g/cm³) — indicador de compactación</p></li>
<li><p><strong>Dr</strong> = Masa seca / Volumen de sólidos — ≈ 2.65 g/cm³ en suelos minerales chilenos</p></li>
<li><p><strong>Porosidad</strong> P = (1 − Da/Dr) × 100 — % del volumen disponible para agua y aire</p></li>
<li><p><strong>Da &gt; 1.6</strong> en francos → compactación moderada; <strong>Da &gt; 1.8</strong> → severa</p></li>
<li><p>Cada <strong>0.1 g/cm³ de aumento en Da</strong> ≈ <strong>3.8% de pérdida de porosidad</strong></p></li>
<li><p>Necesitamos <strong>Da para convertir θg → θv</strong> (próxima sesión)</p></li>
<li><p>La Da es <strong>modificable por manejo</strong>: reducir tráfico, aumentar MO, subsolar</p></li>
</ol>
</section>
<section id="para-la-próxima-sesión" class="slide level2 center">
<h2>Para la próxima sesión</h2>
<p><strong>Sesión 2.3:</strong> Contenido de humedad del suelo y parámetros hídricos</p>
<p>→ θg, θv, Saturación, Capacidad de Campo, Punto de Marchitez Permanente.</p>
<p>→ Ya tenemos Da y P. Ahora calculamos <strong>cuánta agua</strong> hay realmente.</p>
</section>
<section id="preguntas-de-autoevaluación" class="slide level2 center smaller">
<h2>Preguntas de autoevaluación</h2>
<ol type="1">
<li><p>¿Cuál es la diferencia entre Da y Dr? ¿Por qué Da siempre es menor que Dr?</p></li>
<li><p>Un suelo tiene Da = 1.5 g/cm³ y Dr = 2.65 g/cm³. Calcule P. ¿Qué volumen de agua (mm) cabe en los poros de 1 m de profundidad a saturación?</p></li>
<li><p>¿Por qué un suelo arcilloso tiene menor Da que uno arenoso?</p></li>
<li><p>¿Cómo cambia Da cuando un suelo se compacta? ¿Y la porosidad? Dé valores numéricos.</p></li>
<li><p>Describa el método del cilindro para determinar Da. Mencione 3 fuentes de error.</p></li>
<li><p>¿Por qué necesitamos Da para calcular θv a partir de θg?</p></li>
<li><p>Un agricultor nota que sus raíces no pasan de 40 cm. Mide Da = 1.75 g/cm³ a 40-50 cm. ¿Qué problema identifica y qué solución propone?</p></li>
</ol>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>TAG2027 — Relación Suelo Agua Planta | UDLA</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="unidad-02_sesion-02_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="unidad-02_sesion-02_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="unidad-02_sesion-02_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="unidad-02_sesion-02_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="unidad-02_sesion-02_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="unidad-02_sesion-02_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="unidad-02_sesion-02_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="unidad-02_sesion-02_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="unidad-02_sesion-02_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="unidad-02_sesion-02_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>